### ISSUE TITLE
0 examples found

### ISSUE THREAD

**Issue by MMore** [nogates/vigia#17]
I tried it with a simple RAML file of us and rspec 3.3.0. I followed the README. But when I execute `rake spec:vigia` I just get:

```
% >. rake spec:vigia                                                                                                                                                api_storefinder/
No examples found.
Starting Vigia::RSpec

Finished in 0.0003 seconds (files took 0.56533 seconds to load)
0 examples, 0 failures
```

When I invalidate the raml file by adding random chars I get an error. So the file is read and properly parsed.

Any idea?

**Comment by nogates** [comment]
Hello @MMore, could you please paste the content of the RAML file you are using?  It seems like Vigia didn't find any resource or action in your RAML file... 

Also, which version of RAML are you using? Currently, Vigia only supports version `0.8`, although I am planning in supporting `1.0` in the following months.

**Comment by MMore** [comment]
Hey @nogates 

this is our raml:

```raml
#%RAML 0.8
title: API
baseUri: http://localhost:9292
protocols: [ HTTP, HTTPS ]
mediaType: application/json

/find_pos:
  description: Finds and returns stores between two points defined by lat and lng.
  get:
    queryParameters:
      map_bounds:
        description: Maps boundaries with two lat/lng points.
        type: string
        example: "((52.48675300749431,13.35877465576175),(52.54420821064123,13.444605344238312))"
```

**Comment by nogates** [comment]
I am afraid that the problem is that there is not enough information in the RAML file to generate the tests. 

Specifically, Vigia needs that every method/endpoint that is going to be tested (in this case `GET /find_pos`), has at least one response that will be used and compare with the result of the generated request.

For example, if you are expecting the server to return a `200` status response with a simple JSON, you will need to have something like this in your RAML file

```raml
#%RAML 0.8
title: API
baseUri: http://localhost:9292
protocols: [ HTTP, HTTPS ]
mediaType: application/json

/find_pos:
 description: Finds and returns stores between two points defined by lat and lng.
 get:
   queryParameters:
     map_bounds:
       description: Maps boundaries with two lat/lng points.
       type: string
       example: "((52.48675300749431,13.35877465576175),(52.54420821064123,13.444605344238312))"
   responses:
     200:
       body:
          application/json:
            schema: |
              {
                "json" : null
              }
```

In this example, after completing the request, Vigia will compare the server response and fail if its status is not `200` and if its the returned `content_type` header is not `application/json`. Vigia should support multiple response statuses as well as multiple content types.

Hope this makes sense to you

**Comment by MMore** [comment]
Hi @nogates,

I cleaned my example RAML a little bit too much. Sorry for this.

```raml
#%RAML 0.8
title: API
baseUri: http://localhost:9292
protocols: [ HTTP, HTTPS ]
mediaType: application/json
schemas:
  - Stores_find_pos: !include schemas/stores_find_pos.json
  - Errors:          !include schemas/errors.json

resourceTypes:
  - collection:
      get:
        description: The collection of <<resourcePathName>>
        responses:
          200:
            description: OK
            body:
              application/json:
                schema: <<resourceName | !pluralize>>
          400:
            description: Bad Request
            body:
              application/json:
                schema: Errors

/find_pos:
  type: { collection: { resourceName: Store_find_pos } }
  description: Finds and returns stores between two points defined by lat and lng.
  get:
    queryParameters:
      map_bounds:
        description: Maps boundaries with two lat/lng points.
        type: string
        example: "((52.48675300749431,13.35877465576175),(52.54420821064123,13.444605344238312))"
```

So the problem seems to be that the resource type is not properly rendered.

**Comment by nogates** [comment]
> So the problem seems to be that the resource type is not properly rendered.

Exactly.

Currently Vigia uses Coub's RAML parser (https://github.com/coub/raml_ruby), and as you said, the responses defined by the `resourceType` are not being included. I've got some clues about why this is happening and I might try to create a PR in coub's repo to solve this... although, not sure how soon will this be...
