### ISSUE TITLE
Allow optional payload for DELETE requests

### ISSUE THREAD

**Issue by joanniclaborde** [nogates/vigia#22]
Hello, it's me again 😄 

It would be great to allow DELETE requests to send the body payload, if it's specified in the RAML file. It is [permitted by RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3.5) and [required by JSON API](http://jsonapi.org/format/#crud-updating-to-many-relationships).

Thanks!

**Comment by nogates** [comment]
Hi @joanniclaborde :)

Thanks for pointing this out. You are rigth, `DELETE` request should use a payload if provided.

However, I am currently on holidays. I will be back in a few days, but until then, I am afraid I won't be able to fix this. Although, i could review and merge a PR if you want to create one :)

**Comment by joanniclaborde** [comment]
Thanks for the reply! I forked your repo last week for testing, but didn't get to add tests yet. I created the PR for now.

**Comment by joanniclaborde** [comment]
Tests are added. Enjoy your time off!!

**Comment by nogates** [comment]
Thanks a lot for the PR. I just merged it although I can't releaese a new version until I get home. Also, the api blueprint adpater has the same problem so I probably will end refactor it a bit

**Comment by joanniclaborde** [comment]
Great, thanks a lot! I'll keep using my fork until this new code is released.
