### ISSUE TITLE
NameError: uninitialized constant RSpec::Support

### ISSUE THREAD

**Issue by 1st8** [nogates/vigia#25]
Hey,

I am having trouble getting vigia to work in my project.
Upon running the default rake task example, it fails with the following:

```
$ RAILS_ENV=test bundle exec rake spec:vigia
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'vigia'.
/config/application.rb:21:in `<top (required)>'
/rakefile:5:in `require'
/rakefile:5:in `<top (required)>'
NameError: uninitialized constant RSpec::Support
/config/application.rb:21:in `<top (required)>'
/rakefile:5:in `require'
/rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
```

From my Gemfile.lock

```
    rspec (2.14.1)
      rspec-core (~> 2.14.0)
      rspec-expectations (~> 2.14.0)
      rspec-mocks (~> 2.14.0)
    rspec-core (2.14.8)
    rspec-expectations (2.14.5)
      diff-lcs (>= 1.1.3, < 2.0)
    rspec-mocks (2.14.6)
    rspec-rails (2.14.2)
      actionpack (>= 3.0)
      activemodel (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 2.14.0)
      rspec-expectations (~> 2.14.0)
      rspec-mocks (~> 2.14.0)
```

I tried requiring rspec and spec_helper in the Rake task, but it didnt help.
Do you have any idea? Wrong rspec version maybe?

Cheers!

**Comment by nogates** [comment]
Hello @1st8! Sorry it took me a while to respond to this.

Yes, you are correct. Vigia needs `rspec 3.0.0` or above, since it needs the new way to define rspec formatters introduced at that major version.

I guess I should force the rspec version to avoid this. I will create a PR shortly.

**Comment by 1st8** [comment]
Thanks for the feedback!
