### ISSUE TITLE
rake: don't know how to build task 'spec:vigia'

### ISSUE THREAD

**Issue by derlin** [nogates/vigia#26]
I am a newbie in ruby and I can't figure out how to run vigia. 

What I did:
- create a directory for my project
- add a Gemfile with the vigia dependency (as stated in the readme, with the 'group' option)
- run `bundle install`
- add a Rakefile : `task default: 'spec:vigia'`
- add the vigia task from the readme in `lib/tasks/vigia.rake` (note: I am using it with raml)
- run `rake`, `rake spec:vigia`, ...

Impossible to make it work ! I always ends up with the same error:

```
rake aborted!
Don't know how to build task 'spec:vigia' (see --tasks)
```

Am I doing something wrong ? Is it possible to add a better/more precise example of how to use vigia ?

**Comment by nogates** [comment]
Hello @derlin,

You need to import the rake file where the vigia task is defined, at the beginning of your `Rakefile`:

```
import 'lib/tasks/vigia.rake'

task default: 'spec:vigia'
```

Note that this is not an specific error of Vigia. However, I guess it wouldn't hurt to add it to the `README` :-)

**Comment by nogates** [comment]
I guess that you have already solved the issue. Closing this
