### ISSUE TITLE
Support yaml format (Swagger)

### ISSUE THREAD

**Issue by prokopsimek** [nogates/vigia#28]
Add support for yaml formatted docs.

**Comment by nogates** [comment]
@prokopsimek are you referring to this spec: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0-rc0/versions/3.0.md? 

If so, I think supporting the openapis format (which is basically the swagger 2.0 format with new things), would be a nice addition, but if this is just about supporting old swagger files, I think that there are lot of tools out there which already provide the functionality of generating test based on the swagger config.
